### ISSUE TITLE
Plan to release 1.4.x ?

### ISSUE THREAD

**Issue by thanosp** [twigphp/twig-cache-extension#2]
This repo still lacks a stable version. I see on packagist it's registered as 1.4.x-dev
@fabpot I think this could use some attention from the twig organisation as currently the old repo [asm89/twig-cache-extension](https://github.com/asm89/twig-cache-extension) is still receiving issues and is used more widely.

**Comment by fabpot** [comment]
@asm89 Can you have a look at making a release?

**Comment by fabpot** [comment]
1.5 released
