### ISSUE TITLE
Compilation should be deterministic

### ISSUE THREAD

**Issue by stof** [twigphp/twig-cache-extension#5]
Currently, the generated variables for the compiled code are using an increment based on a static property. But this means that the output of the template compilation depends on the order of compilation (as it depends of how many CacheNode have been compiled previously in the same PHP process).
This should be changed to rely on `\Twig_Compiler::getVarName` instead to get a variable name, which ensure determinism by resetting the salt it uses at the beginning of the compilation of each template.

**Comment by fabpot** [comment]
Fixed in https://github.com/twigphp/Twig/pull/3459
